# Generated by Django 2.1.7 on 2019-03-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-username']},
        ),
    ]
