# Generated by Django 2.1.7 on 2019-03-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20190302_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='__', max_length=200, null=True),
        ),
    ]
