# Generated by Django 2.1.7 on 2019-03-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(null=True),
        ),
    ]
