# Generated by Django 2.1.7 on 2019-03-04 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20190304_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthinfo',
            old_name='BMI',
            new_name='bmi',
        ),
        migrations.RenameField(
            model_name='healthinfo',
            old_name='Height',
            new_name='height',
        ),
    ]
