# Generated by Django 2.1.7 on 2019-03-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20190304_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='hi', max_length=200),
        ),
    ]
