# Generated by Django 2.1.7 on 2019-03-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20190304_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='__', max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='__', max_length=50),
        ),
    ]
