# Generated by Django 2.1.7 on 2019-04-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20190304_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='__', max_length=50)),
                ('foodID', models.CharField(default='Custom', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Account')),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='type',
            new_name='intensity',
        ),
        migrations.AddField(
            model_name='food',
            name='foodID',
            field=models.CharField(default='Custom', max_length=50),
        ),
    ]
