# Generated by Django 2.1.7 on 2019-04-03 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_food_isdanger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='__', max_length=50)),
                ('time', models.DateTimeField(null=True)),
                ('calories_gained', models.IntegerField()),
                ('foodID', models.CharField(default='Custom', max_length=50)),
                ('isDanger', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Account')),
            ],
        ),
    ]
