# Generated by Django 2.1.7 on 2019-04-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_healthinfo_caloriesperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='intensity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories_gained',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
