# Generated by Django 2.1.7 on 2019-03-02 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('userID', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('calories_burned', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('calories_gained', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='food.Account')),
                ('firstName', models.CharField(max_length=10, null=True)),
                ('lastName', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=100, null=True)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('healthTarget', models.IntegerField(null=True)),
                ('foodTimeLapse', models.IntegerField(null=True)),
                ('waterTimeLapse', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Account'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Account'),
        ),
    ]
