# Generated by Django 2.1.7 on 2019-03-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
