# Generated by Django 2.1.7 on 2019-03-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20190302_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
