# Generated by Django 2.1.7 on 2019-03-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_account_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
